# Generated by Django 3.1.2 on 2023-05-12 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measurement', '0002_auto_20230512_1658'),
    ]

    operations = [
        migrations.AlterField(
            model_name='measurement',
            name='screen',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
